
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 1.06
name: Archive-Builder
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
  Test::ClassAPI: 1.02
  Class::Inspector: 1.11
requires: 
  Class::Autouse: 1.04
  IO::Zlib: 0
  IO::Scalar: 2.104
  File::Spec: 0.80
  File::Flat: 0.92
  perl: 5.005
  List::Util: 1.15
  Params::Util: 0.10
  Class::Inspector: 1.11
abstract: File generation and archiving framework
