# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Archive-Builder
version:      1.04
version_from: lib/Archive/Builder.pm
installdirs:  site
requires:
    Class::Autouse:                1.04
    Class::Inspector:              1.06
    File::Flat:                    0.92
    File::Spec:                    0.82
    IO::Scalar:                    2.104
    IO::Zlib:                      0
    List::Util:                    1.11
    Test::ClassAPI:                1.02
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
